version: '3'
services:
 app1:
  container_name: api.local
  image: local-develop-environment
  ports:
    - "8080:8080"
  volumes:
    - "${GOPATH}/src:/root/go/src"
    - "./tmp/go-cache:/root/.cache/go-build"
    - "~/.aws:/root/.aws"
    - "./tmp/cloudfront:/tmp/aws"
    - "~/.gitconfig:/root/.gitconfig"
  privileged: true
  environment:
    AWS_PROFILE: $AWS_PROFILE
    TZ: "Asia/Tokyo"
  networks:
    develop:
      ipv4_address: 173.21.6.31
 app2:
  container_name: api2.local
  image: local-develop-environment
  ports:
    - "8081:8081"
  volumes:
    - "${GOPATH}/src:/root/go/src"
    - "./tmp/go-cache:/root/.cache/go-build"
    - "~/.aws:/root/.aws"
    - "./tmp/cloudfront:/tmp/aws"
    - "~/.gitconfig:/root/.gitconfig"
  privileged: true
  environment:
    AWS_PROFILE: $AWS_PROFILE
    TZ: "Asia/Tokyo"
  networks:
    develop:
      ipv4_address: 173.21.6.32
 
networks:
  develop:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 173.21.0.0/16
